os:
- linux
dist: trusty
language: node_js
node_js:
- '6'
- '7'
before_install:
- npm config set progress=false
script: make travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  api_key:
    secure: LSfjJTmLEKnTGjKNFdOZmdGiS8AZdakZzBM5EQByYoE0Zeuh5VDHA0UiDIj17NHGDOpvV7ABaz0Tfy8v4GM0+AwzR0g7V1rIB8/IUNQLiojZTgM0SVTlRRAk6EYWD1EtR6swugSqwYFnrNvwRtxAVAEz4W6ZR4pVFII18VhqtcDo2NzB5uSfcHun8cnAgCcT9cnNiMqpM9ihb8jxfhP12AkVQFuFAyOtnFXSy4to2H2SIvUWWu0rVPrvOQaB6OwHMTeWKETQtg9Fn3Y5KnvwmA3ADdat+y31s4JqSc4JdNjSyAzt/UKhDfw3NNFpNYY5dd+00FesNnPEMZ8p6JaJdyzhF9zDtbKpy2MHJY/WuqDr1P5+eMFGvyLdu9y9O3271mML7ZxXrf7F5TVxxm9jMjKTVVbgwF6KVd3lXMNCcZ+UNbgbq43+mpG9YM9oagQhdFXIVgWXXLBd2GUXb/Ch7Lue6p5Qi/Y1cfQMW87NvoOlSBq4mD4pQ7IdBsIAi+PKCGYtWlS7uHYeUuL5sefG/sti8pljJdk5luvkUnse3cI7Y6CZYv9KJ1Cs809FXo/nDrNJqj2tPxA+lq5TtqlUVHfa/czv5nv9QcfvWVi4d8vL3EzjebIFd8r9KE25CWtCjAO5xRbRC/d3sAse65J3TuwPif2TvGvRSY6fzqD7ICc=
