os:
  - linux
  - osx
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: node_js
node_js:
  - '4'
before_script:
  - npm install -g grunt-cli
  - grunt build
after_success:
  - npm run coveralls
