os:
  - linux
  - osx
dist: trusty
language: node_js
node_js:
  - '6'
before_install:
- npm config set progress=false
script: npm run cover
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls