host:
  compiler:
    =host-mac: clang
    =host-linux: gcc
    =host-win: msvc
tools:
  ninja:
    version: 1.7.1
    url: https://github.com/ninja-build/ninja/releases/download/v${version}/ninja-${host.name}.zip
  clang:
    bin: $(which gcc)
  gcc:
    bin: $(which gcc)
  cmake:
    bin: $(which cmake)
architectures:
  auto: $host.targets.${host.architecture}
  x64:
    architecture: x64
    endianness: LE
  arm64:
    architecture: arm64
    endianness: LE
  armv7:
    architecture: armv7
    float: hard
  armv6:
    architecture: armv7
    float: hard
build:
  =:
    $host.name:
      $host.architecture: $architectures.auto
  =ios:
    ios:
      arm64: $architectures.arm64
      simulator:
        =: $architectures.auto
        +:
          options:
            simulator: true
      +legacy:
        armv7a: $architectures.armv7
        armv6: $architectures.armv6
