host:
  compiler:
    =host-mac: clang
    =host-linux: gcc
    =host-win: msvc
tools:
  ninja:
    version: 1.7.1
    url: https://github.com/ninja-build/ninja/releases/download/v${version}/ninja-${host.platform}.zip
  clang:
    bin: $(which gcc)
  gcc:
    bin: $(which gcc)
  cmake:
    bin: $(which cmake)
architectures:
  auto:
    architecture: $host.architecture
    endianness: $host.endianness
    platform: $host.platform
  x64:
    architecture: x64
    endianness: LE
  arm64:
    architecture: arm64
    endianness: LE
  armv7:
    architecture: armv7
    float: hard
  armv6:
    architecture: armv7
    float: hard
build:
  =:
    $host.platform: $architectures.auto
  =ios:
    arm64:
      extend<:
        source: $architectures.arm64
        arg:
          platform: ios
    simulator:
      extend<:
        source: $architectures.auto
        arg:
          platform: ios
          options:
            simulator: true
    +legacy:
      armv7a: $architectures.armv7
      armv6: $architectures.armv6
