target>:
  output:
    type: static
    lipo: false
  glob:
    assets:
      images: ['**/*.{png, jpg, jpeg, tiff, ico, svg, bmp}']
      fonts: ['**/*.{ttf, otf, woff, woff2}']
    headers: ['**/*.{h, hh, hpp, hxx, ipp}', '!test*/**']
    sources: ['**/*.{cpp, cc, c}', '!**/*.test.*', '!test*/**']
    tests: ['test*/*.{cpp, cc, c}', '**/*.test.*']
  sdk:
    =host-mac:
      $<:
        allSDKs: $(xcodebuild -showsdks)
      =mac:
        device:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /macOS SDKs:/{p=1}' | awk '{print $4}')
          path: $(xcodebuild -version -sdk ${version} Path)
      =ios:
        device:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /iOS SDKs:/{p=1}' | awk '{print $4}')
          path: $(xcodebuild -version -sdk ${version} Path)
        simulator:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /iOS Simulator SDKs:/{p=1}' | awk '{print $6}')
          path: $(xcodebuild -version -sdk ${version} Path)
      =tv:
        device:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /iOS SDKs:/{p=1}' | awk '{print $4}')
          path: $(xcodebuild -version -sdk ${version} Path)
        simulator:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /iOS Simulator SDKs:/{p=1}' | awk '{print $6}')
          path: $(xcodebuild -version -sdk ${version} Path)
          tvOS:
      =watch:
        device:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /watchOS SDKs:/{p=1}' | awk '{print $4}')
          path: $(xcodebuild -version -sdk ${version} Path)
        simulator:
          version: $(echo "${allSDKs}" | awk '/^$/{p=0};p; /watchOS Simulator SDKs:/{p=1}' | awk '{print $6}')
          path: $(xcodebuild -version -sdk ${version} Path)
  flags:
    compiler:
      =clang:
        =linux:
          target: ${settings.clang.arch.${environment.target.architecture}}-unknown-linux
        =mac:
          target: ${settings.clang.arch.${environment.target.architecture}}-apple-darwin
          isysroot: ${sdk.device.path}
        =ios:
          target: ${settings.clang.arch.${environment.target.architecture}}-apple-darwin
          isysroot: ${sdk.device.path}
          miphoneos-version-min: \=6.1
          +simulator:
            target: x86_64-apple-darwin
            mios-simulator-version-min: \=6.1
            isysroot: ${sdk.simulator.path}
    cpp:
      O: 2
      +mac, ios: 
        std: c++11
        stdlib: libc++
      +linux:
        std: c++0x
        pthread: true
    linker:
      =linux:
        lstdc++: true
        lpthread: true
      =mac, ios:
        lc++: true
    frameworks:
      =mac, ios:
        CoreFoundation: true
    make:
      configure:
        enable-static: true
        disable-shared: true
        with-pic: true
