keywords:
  environment:
    - debug
    - production
  host:
    - mac
    - win
    - linux
    - raspbian
    - debian
    - ubuntu
  target:
    - linux
    - mac
    - win
    - ios
    - android
    - raspberryPi
    - test-platform
  sdk:
    - cocoa
    - sdl
    - juce
  architecture:
    - x86
    - x64
    - arm
    - arm64
    - mips
    - mipsel
    - mips64
    - mips64el
    - ppc
    - ppc64
    - s390
    - s390x
    - x87
    - test-arch
  compiler:
    - clang
    - gcc
    - msvc
  ide:
    - xcode
    - clion
    - visualStudio
    - vscode
    - codeblocks
    - appcode
  deploy:
    - simulator
plugins:
  cmake: tmake-plugin-cmake
  make: tmake-plugin-make
  create: ''
  replace: ''
  shell: ''
defaults:
  glob:
    assets:
      images: ['**/*.png', '**/*.jpg', '**/*.jpeg', '**/*.tiff', '**/*.ico', '**/*.svg', '**/*.bmp']
    fonts: ['**/*.ttf', '**/*.otf', '**/*.woff', '**/*.woff2']
    headers: ['**/*.{h, hh, hpp, hxx, ipp}']
    sources: ['**/*.cpp', '**/*.cc', '**/*.c', '!test/**', '!tests/**', '!**/*.test.*']
  host:
    compiler:
      c:
        =host-mac: clang
        =host-linux: gcc
        =host-win: msvc
      cpp: $c
    tools:
      ninja:
        version: 1.7.1
        url: https://github.com/ninja-build/ninja/releases/download/v${version}/ninja-${host.platform}.zip
      +host-mac:
        clang:
          bin: $(which gcc)
      +host-linux:
        gcc:
          bin: $(which gcc)
  target>:
    flags:
      compiler:
        =clang:
          =mac:
            arch: x86_64
          =ios:
            arch: arm64
            isysroot: ${CROSS_TOP}/SDKs/${CROSS_SDK}
            miphoneos-version-min: \=${SDK_VERSION}
            simulator:
              mios-simulator-version-min: \=6.1
              isysroot: ${CROSS_TOP}/SDKs/${CROSS_SDK}
      cxx:
        O: 2
        +mac: 
          std: c++11
          stdlib: libc++
        +linux:
          std: c++0x
          pthread: true
      linker:
        =linux:
          lstdc++: true
          lpthread: true
        =mac:
          lc++: true
      frameworks:
        =mac: 
          CoreFoundation: true
      make:
        configure:
          enable-static: true
          disable-shared: true
          with-pic: true
