apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: queue-port
    port: 5672
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: cluster-port
    port: 4369
  - name: dist-port
    port: 25672
---
apiVersion: v1
kind: Service
metadata:
  name: rmq-cluster
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
  - name: queue-port
    port: 5672
  - name: cluster-port
    port: 4369
  - name: dist-port
    port: 25672