apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    name: vault
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8200
      targetPort: 8200
  selector:
    app: vault