os:
- linux
- osx
dist: trusty
language: node_js
node_js:
- '6'
before_install:
- npm config set progress=false
script: npm run travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  on:
    branch: release
  email: structuresound@gmail.com
  skip_cleanup: true
  api_key:
    secure: fR8zPV59CIjW3NniwReGWZ4IHDxbl4VJNjGFFsV+TwMcmOek+pYRJR58sZdZ+2E+CI0zdffa9Bd65WPHcHX3J5j00okSQXNYcASIT/8sfcQG2lQhZ7Ijz5G1v6wCJLec8WUILiylREqzBZzh3SPzW6DidNbdvNVbxpN3CKfz3yhECbtUzc5Vm4p/kwRbRhM9hVmK3Z+9amLXxpI9HG37rClhpetMhLmrdrVnQo0pSL6Rwm2EpHf9MR7evWkDmYxsd8zXHZ0XWkQJMrid2iEEuAjMUFIgejIAbM02zoCKrraQf62VhzTewLObucSYeGpfMglfwgDX9IjyVZVOwUFt+xO0aHrIA7vklh1rMxKcoUzLbcfDVvq+DPrJoP89dg7oQBPKj+d1sndaqAeEBKWuCGzyPb0Gb3gjiI4hzs0qtQZFMQXmAMOvyWOqQ/tlchalyRai8qyDqyojkRSZCb/F9oxdUtDtTDCT4UpX7QuSleyX3b5o1NoGoG3+4D4EheMhoZJsV9qTxHC5COHyqskJMdNf06fQGl2HgGeD7yzdiqtkgGKBTPW6XLG3qQUpJUBkJIYw3ActmOP8VgW2MzI76GUOfUqKlJLfXQ5PaQrl1bVqhbTDNwuEuMFACeNbFKKfHk7RurwIoJxaTZvcBRIjBUDnaAmaU4iHt5dqFGazhC0=