os:
- linux
dist: trusty
language: node_js
node_js:
- '6'
- '7'
before_install:
- npm config set progress=false
script: npm run travis
after_script:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls