version: '2'
services:
  web:
    container_name: 'tmake_server'
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    container_name: 'tmake_db'
    image: chromapdx/mongo-rocks
    volumes:
      - ./:/data
    ports:
      - "27017:27017"
