apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 20%
  minReadySeconds: 1
  template:
    metadata:
      name: front
      labels:
        app: front
    spec:
      imagePullSecrets:
      - name: ecr-secret
      volumes:
      - name: front
        secret:
          secretName: front
      containers:
      - name: front
        image: GRUNT_FRONT_IMAGE
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 192Mi
            cpu: 250m
        ports:
        - name: front-http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: front-http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        - name: SETTINGS
          valueFrom:
            secretKeyRef:
              name: front
              key: settings.yaml
        - name: NAMESPACE_SETTINGS
          valueFrom:
            secretKeyRef:
              name: namespace
              key: settings.yaml