kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ingress-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.8
        name: ingress-controller
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 192Mi
            cpu: 150m
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/front
        - --configmap=$(POD_NAMESPACE)/ingress-controller-sticky
        - --watch-namespace=$(POD_NAMESPACE)