apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 20%
  minReadySeconds: 1
  template:
    metadata:
      name: mailer
      labels:
        app: mailer
    spec:
      imagePullSecrets:
      - name: ecr-secret
      volumes:
      - name: mailer
        secret:
          secretName: mailer
      containers:
      - name: mailer
        image: GRUNT_MAILER_IMAGE
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 150m
        ports:
        - name: mailer-http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: mailer-http
          initialDelaySeconds: 30
          timeoutSeconds: 1
        env:
        - name: SETTINGS
          valueFrom:
            secretKeyRef:
              name: mailer
              key: settings.yaml
        - name: NAMESPACE_SETTINGS
          valueFrom:
            secretKeyRef:
              name: namespace
              key: settings.yaml