apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: theme
  labels:
    app: theme
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 20%
  minReadySeconds: 1
  template:
    metadata:
      name: theme
      labels:
        app: theme
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
        - name: theme
          image: GRUNT_THEME_IMAGE
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - name: nginx-http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /theme/theme.json
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1