apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: wordpress-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: wordpress-mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wordpress-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi