apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: nginx-http
    protocol: TCP
    name: http
  - port: 443
    targetPort: nginx-https
    protocol: TCP
    name: https
  selector:
    app: web